from enum import Enum

class FireListPersonType(Enum):
    ATTENDEE = 'ATTENDEE'
    VOLUNTEER = 'VOLUNTEER'
    GUEST = 'GUEST'

class AttendeeSource(Enum):
    LOCAL = 'LOCAL'
    EVENTBRITE = 'EVENTBRITE'

class APIKeyType(Enum):
    NORMAL = 'NORMAL',
    JOLT = 'JOLT'

class JOLTPrintQueueStatus(Enum):
    QUEUED = 'QUEUED'
    RECEIVED = 'RECEIVED'
    PRINTED = 'PRINTED'
    FAILED = 'FAILED'

class JOLTPrintJobType(Enum):
    ATTENDEE_LABEL = 'ATTENDEE_LABEL'
    TEST_ATTENDEE_LABEL = 'TEST_ATTENDEE_LABEL'

class JOLTRequestType(Enum):
    PRINT_JOB_REQUEST = 'PRINT_JOB_REQUEST'
    PRINT_JOB_RECEIVED = 'PRINT_JOB_RECEIVED'
    PRINT_JOB_COMPLETED = 'PRINT_JOB_COMPLETED'
    PRINT_JOB_ERROR = 'PRINT_JOB_ERROR'
    HEALTHCHECK_REQUEST = 'HEALTHCHECK_REQUEST'
    HEALTHCHECK_RESPONSE = 'HEALTHCHECK_RESPONSE'

class JOLTHealthCheckStatus(Enum):
    PENDING = 'PENDING'
    SUCCESS = 'SUCCESS'
    FAILED = 'FAILED'

class DiscordMessageType(Enum):
    RSVP_REMINDER = 'RSVP_REMINDER'
    RSVP_CONFIRM = 'RSVP_CONFIRM'
    RSVP_EXPIRED = 'RSVP_EXPIRED'

class DiscordMessageView(Enum):
    RSVP_REMINDER_VIEW = 'RSVP_REMINDER_VIEW'
    RSVP_CONFIRM_VIEW = 'RSVP_CONFIRM_VIEW'

class DiscordMessageState(Enum):
    SENT = 'SENT'
    RESPONDED = 'RESPONDED'
    EXPIRED = 'EXPIRED'
    UPDATED = 'UPDATED'