services:
  jams-web:
    image: ghcr.io/jdplays/jams_master:latest
    container_name: jams-web
    command: ./entrypoint.sh
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - SECRET_KEY=${FLASK_SECRET}
      - DATABASE_URL=postgresql://${PG_USER}:${PG_PASS}@jams-db:5432/jams-main
    volumes:
      -/path/to/db_migrations:/jams/migrations
    depends_on:
      - jams-db
  jams-db:
    image: postgres:13
    container_name: jams-db
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
      POSTGRES_DB: jams-main
    volumes:
      - /path/to/db:/var/lib/postgresql/data
